РК3
frontend-park-mail-ru/2017_2_JeEs pull request #22
Opened 2017-11-23 21:27 UTC by OkciD

2017-11-23 23:08 UTC, 8coon requested changes

2017-11-23 23:08 UTC, 8coon commented on app/game/entities/figure.ts
>      constructor(fieldDimension: number) {
Можно просто `constructor(private fieldDimension: number)`
[Подробности](https://kendaleiv.com/typescript-constructor-assignment-public-and-private-keywords/)

2017-11-23 23:08 UTC, 8coon commented on app/game/entities/wall.ts
> +            (lowerOrRight.y >= 0 && lowerOrRight.y <= maxCellIndex);
"Это всё идёт у нас л о г и к а, л о г и к а у нас идёт" (с) сами знаете кто

2017-11-23 23:08 UTC, 8coon commented on app/game/game-manager.ts
> +        if (gameMode === "singleplayer") {
switch?

2017-11-23 23:08 UTC, 8coon commented on app/game/gameview/gameviewmanager.ts
> +const WINDOW_WIDTH = window.innerWidth;
window.innerWidth изменяется, но это было бы ещё полбеды. Плохо то, что он иногда внезапно изменяется, вот в чём фокус!

2017-11-23 23:08 UTC, 8coon commented on app/game/gameview/wallview.ts
> +                this._ghostWall[0].rotation.y = Math.PI / 2
Аккуратнее с координатами, молодой человек
Кстати, вы выяснили, в чём была проблема с неожиданным положением стенок? Мне кажется, её корень где-то рядом

2017-11-23 23:08 UTC, 8coon commented on app/game/utils/field-state.ts
>      yield { // thx, Serge Peshkofff
:smirk:

2017-11-23 23:08 UTC, 8coon commented on app/services/fullscreenlogic.js
> +        debugger;
Аккуратнее с дебаггерами, молодой человек

2017-11-23 23:08 UTC, 8coon commented on app/services/fullscreenlogic.js
> +        // element.height = window.innerHeight;
Аккуратнее с комментариями, молодой человек

2017-11-23 23:12 UTC, 8coon commented on app/game/entities/wall.ts
> +            (lowerOrRight.y >= 0 && lowerOrRight.y <= maxCellIndex);
Это всё вообще в каком базисе?

2017-11-23 23:14 UTC, 8coon commented on app/game/entities/wall.ts
> +            (lowerOrRight.y >= 0 && lowerOrRight.y <= maxCellIndex);
По фронту или по срезу?

2017-11-23 23:36 UTC, KOPTE3 commented on app/game/services/transport.ts
> +export default class Transport {
Видел такое у вас в проекте в паре мест. Вы не задумывались о том, чтобы оформить это поведение в виде декоратора: `@singleton`, например?)

Но, разумеется, я вам этого не говорил 🌚

2017-11-23 23:40 UTC, KOPTE3 commented
Кстати, обычно файлы `*.css.map` (и другие файлы с сорсмапами) не добавляют в репозиторий, т.к. эти файлы являются автогенерируемыми

2017-11-24 08:30 UTC, OkciD commented on app/game/game-manager.ts
> +        if (gameMode === "singleplayer") {
crutch)

2017-11-24 09:54 UTC, vileven approved these changes

2017-11-24 09:54 UTC, vileven commented on app/game/gameview/wallview.ts
>      private _checkСollisions(points: Point[]) {
Тут С большая кириллицей)

2017-11-24 09:54 UTC, vileven commented on app/views/gameview/game.css
> +  width: 900;
Укажите единицы измерения)

2017-11-24 11:52 UTC, 8coon approved these changes

2017-11-24 11:52 UTC, merged

2017-11-24 12:09 UTC, 8coon commented
1